# src/config/control.yaml

# COMPLEMENTARY FILTER
filter: 
  # Fusion coefficient alpha
  alpha: 0.975

# PID
pid: 
  # Derivative low-pass filter coefficient
  beta: 0.75
  # --- PID ---
  # Proportional gain
  kp: 1.0
  # Integral gain
  ki: 0.05
  # Derivative gain
  kd: 0.01
  # Intregral limits
  integral_limits: {
    "max": 0.5,
    "min": -0.5,
  }
  # Output duty limits
  output_limits: {
    "max": 1.0,
    "min": -1.0,
  }

# BALANCE CONTROLLER
balance: 
  # Deadband for balancing
  deadband: 0.05
  # Angle offset (radians)
  angle_offset: 0.0
 