# src/config/motors.yaml

# --- ENCODER ---
encoder: 
  # --- Motor Encoder ---
  # Pulses per revolution (per channel)
  encoder_ppr_channel: 11
  # Pin layout (BCM naming)
  motor_encoder_pins: 
    left: 
      # GPIO
      channel_a: 17
      # GPIO
      channel_b: 27
    right: 
      # GPIO
      channel_a: 23
      # GPIO
      channel_b: 24

  # --- Gearbox ---
  # Motor shaft turns per wheel shaft turns
  gear_ratio: 18.75

  # --- Wheels ---
  # Wheel diameter (m)
  wheel_diameter_m: 0.065
  # Wheel 

  # --- Velocity Estimation ---
  # Length tick timestamp buffer 
  length_tick_buffer: 20
  # Velocity low-pass filter coefficient alpha
  alpha: 0.4

# --- DRIVER ---
driver:
  # --- Motor IDs ---
  # Motor A = 0 (Left)
  left_motor_id: 0
  # Motor B = 1 (Right)
  right_motor_id: 1

  # I2C address for the SCMD master chip
  i2c_address: 0x5D

  # Maximum duty command
  max_duty_float: 1.0
  # SCMD absolute limit
  max_level_hardware: 255 
